In [1]:
import numpy as n
import random

**1. Numpy pgm to convert F degree to Centigrade degree. F are stored in a ndarray**

In [48]:
F = n.array([20,30,40,50])
for i in F:
    print(f"{i}F = {((5/9)*(i-32)).round(2)} C")

20F = -6.67 C
30F = -1.11 C
40F = 4.44 C
50F = 10.0 C


**2. Numpy pgm to create a random array with 1000 elements and compute the avg,variance,sd of array elements.**

In [49]:
ar = n.random.randint(1,2546,1000)
print("Average : ", n.average(ar))
print("Variance : ", n.var(ar))
print("SD : ", n.std(ar))

Average :  1291.989
Variance :  531962.640879
SD :  729.357690628542


**3. Numpy pgm to convert angles from degrees to radians for all elements in a given array**

In [50]:
arr = n.random.randint(0,360,5)
for i in arr:
    print(f"{i} degrees = {n.deg2rad(i).round(2)} radians")


123 degrees = 2.15 radians
115 degrees = 2.01 radians
23 degrees = 0.4 radians
224 degrees = 3.91 radians
128 degrees = 2.23 radians


**4.Numpy pgm to calculate difference bw neighbouring elements elementwise of a given array.**

In [47]:
arr = n.random.randint(0,100,5)
print(arr)
print(n.diff(arr))

[51 37 83 15 27]
[-14  46 -68  12]


**5. Sort a given complex array using real part first and then imaginary part**

In [31]:
print(n.sort_complex([10+2j,2+1j,8.3+3j,5.23+3.4j]))

[ 2.  +1.j   5.23+3.4j  8.3 +3.j  10.  +2.j ]


**6. ID array with random numbers and print the values greater than 4**

In [32]:
arr=n.random.randint(-23,56,6)
print(arr)
print(arr[n.where(arr>4)])

[ 37  34  19  26 -18  -2]
[37 34 19 26]


**7. return random numbers and search particular number given by the user**

In [33]:
ar = n.random.randint(-27,40,8)
print(ar)
i = int(input("Search : "))
print(f"{i} found at {n.where(ar == i) if i in ar else print()} ")

[ -5  -4  10 -26  25 -24   7 -23]
10 found at (array([2]),) 


8. Write a Numpy program to save a given array to a text file and load it

In [34]:
ar = n.random.randint(1,80,5)
t = n.savetxt("file.txt", ar)
t = n.loadtxt("file.txt")
print("Data is ",t)

Data is  [28.  1. 30. 33. 14.]


**9. Create an array of all even intigers from 30 to 60**

In [35]:
print(n.arange(30,61,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


**10. Sum of all elements, each row and each column**

In [36]:
ar = n.random.randint(0,10,(5,5))
print(ar)
print("Sum of all elements : ", n.sum(ar))
print("Sum of rows : ", n.sum(ar, axis=0))
print("Sum of columns : ", n.sum(ar,axis=1))

[[4 0 8 7 6]
 [3 0 6 2 7]
 [3 5 1 6 5]
 [3 8 1 4 3]
 [6 6 7 6 7]]
Sum of all elements :  114
Sum of rows :  [19 19 23 25 28]
Sum of columns :  [25 18 20 19 32]
