In [ ]:
import numpy as np
p = np.array((1,2,3,4))
print(p)
print(type(p))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
p = np.arange(10)
n = np.arange(1,100,2)
print(p)
print(n)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [12]:
arr = np.zeros(3,int)
print(arr)
arr1 = np.ones((3,3),int)
print(arr1)

[0 0 0]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

mat1=np.eye(3)
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
arr = np.arange(1,8)
print(arr)
print(arr[1:5])
print(arr[:5])
print(arr[1:])
print(arr[-4:-1])

[1 2 3 4 5 6 7]
[2 3 4 5]
[1 2 3 4 5]
[2 3 4 5 6 7]
[4 5 6]


In [25]:
a = np.arange(1,6)
b=a
c=a.copy()
a[2]=10
print(a)
print(b)
print(c)

[ 1  2 10  4  5]
[ 1  2 10  4  5]
[1 2 3 4 5]


In [27]:
a = np.array((1,2,3,4,5))
b = np.array((6,7,8,9,10))
print(a)
print(b)
print(np.concatenate((a,b)))

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8],[1,0]])
print(a)
print(b)
print(np.concatenate((a,b),axis=1)) #to concatenate rowwise
#same dimension aanel normal concatenation

[[1 2 3]
 [4 5 6]]
[[7 8]
 [1 0]]
[[1 2 3 7 8]
 [4 5 6 1 0]]


In [ ]:
a=np.array((5,6,7,8,6))
print(np.where(a==6)) #machine index and type returned as a tuple..index array is at tuple index 0
b=np.where(a==6)
print(*b[0]+1) #"*" avoids the list[]

(array([], dtype=int64),)

